stages:
  - mavenbuild
  - maventest
  - deploy

maven-build:
  stage: mavenbuild
  tags:
    - shell
  script:
    - echo "Starting springboot build"
    - cd BackEnd/DatabaseAccessProject
    - chmod 777 *
    - mvn package

maven-test:
  stage: maventest
  tags:
    - shell
  script:
    - echo "Running spring-boot tests"
    - cd BackEnd/DatabaseAccessProject
    - chmod 777 *
    - mvn test

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - echo "Do your deploy here"
    - cd BackEnd/DatabaseAccessProject
    - chmod 777 *
    - mvn package
    - sudo rm -f /home/SS_5/database-access.jar
    - sudo mv target/*SNAPSHOT.jar /home/SS_5/database-access.jar
    - sudo systemctl stop ss-5
    - sudo systemctl start ss-5

