stages:
  - mavenbuild
  - maventest
  - deploy

maven-build:
  stage: mavenbuild
  tags:
    - shell
  script:
    - echo "Starting springboot build"
    - cd BackEnd/DatabaseAccessProject
    - chmod 777 *
    - /usr/maven/apache-maven-3.6.0/bin/mvn package

maven-test:
  stage: maventest
  tags:
    - shell
  script:
    - echo "Running spring-boot tests"
    - cd BackEnd/DatabaseAccessProject
    - chmod 777 *
    - /usr/maven/apache-maven-3.6.0/bin/mvn test

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - echo "Do your deploy here"
    - cd BackEnd/DatabaseAccessProject
    - chmod 777 *
    - /usr/maven/apache-maven-3.6.0/bin/mvn package
    - sudo mv target/*SNAPSHOT.jar /target/spring-boot.jar 
    - sudo systemctl stop systemd-spring-boot
    - sudo systemctl start systemd-spring-boot

