# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: busybox:latest

maven-build:
  stage: mavenbuild
  script:
    - echo "Starting springboot build"
    - cd BackEnd/DatabaseAccessProject
    - chmod 777 *
    - ./mvnw package

maven-test:
  stage: maventest
  script:
    - echo "Running spring-boot tests"
    - cd BackEnd/DatabaseAccessProject
    - ./mvnw test

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
