stages:
  - mavenbuild
  - maventest
  - deploy

maven-build:
  stage: mavenbuild
  tags:
    - shell
  script:
    - cd BackEnd/DatabaseAccessProject
    - chmod 777 *
    - mvn package

maven-test:
  stage: maventest
  tags:
    - shell
  script:
    - cd BackEnd/DatabaseAccessProject
    - chmod 777 *
    - mvn test

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - cd BackEnd/DatabaseAccessProject
    - chmod 777 *
    - mvn package
    - sudo rm -f /home/SS_5/database-access.jar
    - sudo mv target/*SNAPSHOT.jar /home/SS_5/database-access.jar
    - sudo systemctl stop ss-5
    - sudo systemctl start ss-5
  #rules:
    #- if: '$CI_MERGE_REQUEST_TARGET_BRANCH == "master"'
      #when: always
    #- if: '$CI_MERGE_REQUEST_SOURCE_BRANCH'
      #when: never
    #- when: manual

